filebeat.inputs:
- type: log 
  enabled: true 
  paths: 
      - /var/log/apache2/*.log
  fields:
    apache: true
  fields_under_root: true
output.logstash:
  username: filebeat_internal
  password: password
  hosts: ["logstash:5044"]