---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/master/docker/data/logstash/config/logstash-full.yml
#

# xpack.security.enabled: true
# xpack.security.http.ssl.enabled: true
# xpack.security.http.ssl.key: certs/es03/es03.key
# xpack.security.http.ssl.certificate: certs/ca/ca.crt
# xpack.security.http.ssl.certificate_authorities: certs/ca/ca.crt
# xpack.security.http.ssl.verification_mode: certificate
# xpack.security.transport.ssl.enabled=true
# xpack.security.transport.ssl.key=certs/es03/es03.key
# xpack.security.transport.ssl.certificate=certs/es03/es03.crt
# xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
# xpack.security.transport.ssl.verification_mode=certificate
# xpack.license.self_generated.type=${LICENSE}